# Generated by Django 3.0.6 on 2020-06-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(default='', max_length=100)),
                ('emp_code', models.CharField(default='', max_length=8, unique=True)),
                ('emp_photo', models.BooleanField()),
                ('emp_encoding', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(default='', max_length=100)),
                ('emp_code', models.CharField(default='', max_length=8)),
                ('attendance_confi', models.FloatField()),
                ('attendance_date', models.DateField()),
                ('attendance_time', models.TimeField()),
                ('remark', models.CharField(default='None', max_length=100)),
            ],
        ),
    ]
